import jsPDF from 'jspdf'
import autoTable from 'jspdf-autotable'

export function generateEvidencePDF(data: {
  employer: any,
  worker: any,
  application: any,
  wageData: any
}) {
  const doc = new jsPDF()
  const { employer, worker, application, wageData } = data
  const today = new Date().toLocaleDateString('en-CA', {
    year: 'numeric', month: 'long', day: 'numeric'
  })

  // PAGE 1 — COVER
  doc.setFontSize(20)
  doc.setFont('helvetica', 'bold')
  doc.text('LMIA APPLICATION EVIDENCE PACKAGE', 20, 30)
  doc.setFontSize(11)
  doc.setFont('helvetica', 'normal')
  doc.text(`Employer: ${employer.tradingName || employer.companyName}`, 20, 50)
  doc.text(`Legal Name: ${employer.companyName}`, 20, 58)
  doc.text(`CRA BN: ${employer.cra_bn}`, 20, 66)
  doc.text(`Job Title: ${employer.jobTitle} (NOC ${employer.nocCode})`, 20, 74)
  doc.text(`Province: ${employer.province}`, 20, 82)
  doc.text(`Generated: ${today}`, 20, 90)
  doc.text(`LMIABridge Reference: ${application._id}`, 20, 98)

  // PAGE 2 — EMPLOYER VERIFICATION
  doc.addPage()
  doc.setFontSize(16)
  doc.setFont('helvetica', 'bold')
  doc.text('EMPLOYER VERIFICATION', 20, 30)
  doc.setFontSize(11)
  doc.setFont('helvetica', 'normal')
  doc.text('Verification Method: TinyFish Web Agent — Canada Business Registry', 20, 50)
  doc.text(`Status: ${employer.verificationStatus?.toUpperCase()}`, 20, 58)
  doc.text(`Corporation Number: ${employer.corporationNumber || 'Verified'}`, 20, 66)
  doc.text(`Verification Date: ${employer.updatedAt ? new Date(employer.updatedAt).toLocaleDateString() : today}`, 20, 74)

  // PAGE 3 — WAGE COMPLIANCE
  doc.addPage()
  doc.setFontSize(16)
  doc.setFont('helvetica', 'bold')
  doc.text('WAGE COMPLIANCE', 20, 30)
  doc.setFontSize(11)
  doc.setFont('helvetica', 'normal')
  const hourlyOffered = (employer.offeredWage / 2080).toFixed(2)
  const compliant = parseFloat(hourlyOffered) >= (wageData?.medianWage || 0)
  doc.text(`Offered Annual Wage: $${employer.offeredWage?.toLocaleString()}`, 20, 50)
  doc.text(`Offered Hourly Rate: $${hourlyOffered}/hr`, 20, 58)
  doc.text(`ESDC Median Wage (NOC ${employer.nocCode}, ${employer.province}): $${wageData?.medianWage || 'N/A'}/hr`, 20, 66)
  doc.text(`Compliance Status: ${compliant ? 'COMPLIANT — Meets ESDC median wage' : 'NON-COMPLIANT'}`, 20, 74)
  doc.text('Source: Live ESDC data via TinyFish Web Agent', 20, 82)

  // PAGE 4 — ADVERTISING SCHEDULE
  doc.addPage()
  doc.setFontSize(16)
  doc.setFont('helvetica', 'bold')
  doc.text('ADVERTISING SCHEDULE', 20, 30)
  doc.setFontSize(10)
  doc.text('LMIA regulations require advertising on minimum 3 platforms over 4 consecutive weeks.', 20, 42)

  if (application.advertisingSchedule?.length > 0) {
    autoTable(doc, {
      startY: 50,
      head: [['Week', 'Platform', 'Action Required', 'Deadline', 'Status']],
      body: application.advertisingSchedule.map((s: any) => [
        `Week ${s.week}`,
        s.platform,
        s.actionRequired || s.action || '',
        s.deadlineDate || s.deadline || '',
        s.status?.toUpperCase() || ''
      ]),
      styles: { fontSize: 9 },
      headStyles: { fillColor: [0, 100, 80] }
    })
  }

  // PAGE 5 — TRANSITION PLAN
  doc.addPage()
  doc.setFontSize(16)
  doc.setFont('helvetica', 'bold')
  doc.text('TRANSITION PLAN', 20, 30)
  doc.setFontSize(11)
  doc.setFont('helvetica', 'normal')

  if (application.transitionPlan) {
    const plan = typeof application.transitionPlan === 'string'
      ? JSON.parse(application.transitionPlan)
      : application.transitionPlan
    let y = 50
    if (plan.year1) { doc.text(`Year 1: ${plan.year1}`, 20, y, { maxWidth: 170 }); y += 30 }
    if (plan.year2) { doc.text(`Year 2: ${plan.year2}`, 20, y, { maxWidth: 170 }); y += 30 }
    if (plan.year3) { doc.text(`Year 3: ${plan.year3}`, 20, y, { maxWidth: 170 }); y += 30 }
    if (plan.canadianHiringGoals) {
      doc.text(`Canadian Hiring Commitment: ${plan.canadianHiringGoals}`, 20, y, { maxWidth: 170 })
    }
  }

  // PAGE 6 — GTS ELIGIBILITY
  doc.addPage()
  doc.setFontSize(16)
  doc.setFont('helvetica', 'bold')
  doc.text('GLOBAL TALENT STREAM ELIGIBILITY', 20, 30)
  doc.setFontSize(11)
  doc.setFont('helvetica', 'normal')
  doc.text(`GTS Eligible: ${application.gtsEligible ? 'YES' : 'NO'}`, 20, 50)
  doc.text(`Category: ${application.gtsCategory || 'B'}`, 20, 58)
  doc.text('NOC 21232 is listed on the Global Talent Stream Category B occupations list.', 20, 66)
  doc.text(`Processing Time: 14 business days`, 20, 74)
  doc.text(`Minimum Wage Requirement: $80,000/yr — Offered: $${employer.offeredWage?.toLocaleString()} ✓`, 20, 82)

  // FOOTER ON ALL PAGES
  const pageCount = doc.getNumberOfPages()
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i)
    doc.setFontSize(8)
    doc.setFont('helvetica', 'italic')
    doc.text(
      `Generated by LMIABridge | Powered by TinyFish Web Agents | ${today} | Page ${i} of ${pageCount}`,
      20, 285
    )
  }

  return doc
}
